AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes
Layout/LineLength:
  Max: 120
  AllowURI: true
  URISchemes:
    - http
    - https
Style/Encoding:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: true
  Exclude:
    - 'lib/ffaker/address_ja.rb'
    - 'lib/ffaker/address_se.rb'
Style/OptionalBooleanParameter:
  Enabled: false
Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - 'lib/ffaker/bank.rb'
Style/RedundantArgument:
  Enabled: false